#ifndef ENUMS_H
#define ENUMS_H

typedef enum {
    SPHERE=0,
    VERTCYL=1,
    ROTCYL=2,
    RECT1=3,
    RECT2=4,
    FIXEDRECT=5,
    ELLIPSOID=6,
    PLAYER=7,
    UNKNOWNSPHERE=8,
    PUSHWALL=9
} __attribute__((packed)) COLLISIONTYPE;

typedef enum {
    UNIT_POS=1,
    UNIT_ANG=2,
    UNIT_SCL=4,
    HIDE=8,
    BREAK=16,
    ZXY_ANG=32,
    SKIP=64,
    SHAPE_SKIP=128,
    CLIP=256,
    MODIFIER=512
} __attribute__((packed)) NJD_EVAL;

typedef enum {
    NJD_CONTROL_3D_DISP_AXIS=1,
    NJD_CONTROL_3D_NO_CLIP_CHECK=2,
    NJD_CONTROL_3D_CONSTANT_ATTR=4,
    NJD_CONTROL_3D_ENABLE_ALPHA=8,
    NJD_CONTROL_3D_CONSTANT_MATERIAL=16,
    NJD_CONTROL_3D_OFFSET_MATERIAL=32,
    NJD_CONTROL_3D_DEPTH_QUEUE=64,
    NJD_CONTROL_3D_VERTEX_OFFSET=128,
    NJD_CONTROL_3D_MODEL_CLIP=256,
    NJD_CONTROL_3D_CONSTANT_TEXTURE_MATERIAL=512,
    NJD_CONTROL_3D_SHADOW=1024,
    NJD_CONTROL_3D_CNK_CONSTANT_ATTR=2048,
    NJD_CONTROL_3D_SHADOW_OPAQUE=4096,
    NJD_CONTROL_3D_TRANS_MODIFIER=8192,
    NJD_CONTROL_3D_USE_PUNCHTHROUGH=16384,
    NJD_CONTROL_3D_CNK_BLEND_MODE=32768,
    NJD_CONTROL_3D_DISABLE_NEAR_CLIP=65536,
    NJD_CONTROL_3D_ENV_UV_SCROLL=131072,
    NJD_CONTROL_3D_MIRROR_MODEL=2147483648
} __attribute__((packed)) NJD_CONTROL_3D;

#endif // ENUMS_H